name: CI-integration

on:
  push:
    branches:
    - develop

  workflow_dispatch:
env:
  MSG: HELLO
jobs:
  Static-Code-Analyze:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "running build"
      - if: env.MSG == 'HELLO1'
        run: |
          echo running