name: CI-dev

on:
  push:
    branches:
    - develop

  workflow_dispatch:
env:
  MSG: HELLO
jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      jira_ticket_sum: ${{ steps.test.outputs.msg }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - id: test
        run: |
          echo  echo ::set-output name=msg::
      - name: get commit sha
        run: |
          # get the latests commit sha for building images
          echo "GITHUB_SHA_SHORT=$(echo $(git rev-parse HEAD) | cut -c 1-7)" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
      - run: |
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
      - run: |
          echo "running build"
          echo "GITHUB_SHA_SHORT=AA" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
          echo "GITHUB_SHA_SHORT2: ${{ env.GITHUB_SHA_SHORT }}"
      - if: env.GITHUB_SHA_SHORT == 'AA'
        run: |
          echo running ${{ env.GITHUB_SHA_SHORT }}
  success:
    runs-on: ubuntu-latest
    steps:
      - id: slack-passed
        run: |
          echo "succeed"
          echo ">>${{needs.ci.outputs.msg}}"