name: CI-integration

on:
  push:
    branches:
    - develop

  workflow_dispatch:
env:
  MSG: HELLO
jobs:
  Static-Code-Analyze:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "running build"
          echo "GITHUB_SHA_SHORT=AA" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
      - if: env.GITHUB_SHA_SHORT == 'AA'
        run: |
          echo running ${{ env.GITHUB_SHA_SHORT }}