name: CI-integration

on:
  push:
    branches:
    - develop

  workflow_dispatch:
env:
  MSG: HELLO
jobs:
  Static-Code-Analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get commit sha
        run: |
          # get the latests commit sha for building images
          echo "GITHUB_SHA_SHORT=$(echo $(git rev-parse HEAD) | cut -c 1-7)" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
      - run: |
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
      - run: |
          echo "running build"
          echo "GITHUB_SHA_SHORT=AA" >> $GITHUB_ENV
          echo "GITHUB_SHA_SHORT: ${GITHUB_SHA_SHORT}"
      - if: env.GITHUB_SHA_SHORT == 'AA'
        run: |
          echo running ${{ env.GITHUB_SHA_SHORT }}