name: getIP

on:
  # push:
  #   branches: 
  #   - develop
  #   - master
  # pull_request:
  #   branches:
  #   - master
  #   - develop

  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - run: |
          curl -sSf ipinfo.io/ip
