name: test

on:
  workflow_dispatch:

env:
  IMAGE_TAG_ADD: intergration
  JENKINS_INTEG_URL: 'https://130.211.58.18/view/CRM%20CI%20CD/job/CRM-AUTO/build\?token\='

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      o1: ${{ steps.te.outputs.test }}
    steps:
      - id: te
        run: |
          env
      - name: testing
        id: test
        run: |
          echo "${{ secrets.JENKINS }} ${{ env.JENKINS_INTEG_URL }}${{ secrets.JENKINS_JOB_TOKEN }}"
          curl -sSfL -m 15 -u '${{ secrets.JENKINS }}' ${{ env.JENKINS_INTEG_URL }}${{ secrets.JENKINS_JOB_TOKEN }}
  tes:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          if [ -z "${{ needs.tet.outputs.o1 }}" ];then
            echo empty
          fi
          echo ">>${{ needs.tet.outputs.o1 }}"

