name: testing

on:
  workflow_dispatch:

env:
  IMAGE_TAG_ADD: intergration

jobs:
  tet:
    runs-on: ubuntu-latest
    outputs:
      o1: ${{ steps.te.outputs.test }}
    steps:
      - name: testing
        id: test1
        run: |
            env

      - id: te
        run: |
          env
  tes:
    needs: tet
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          if [ -z "${{ needs.tet.outputs.o1 }}" ];then
            echo empty
          fi
          echo ">>${{ needs.tet.outputs.o1 }}"

