name: CI

on:
  # schedule:
  #   - cron:  '0 */2 * * *'
  push:
    branches: 
    - main 
  pull_request:
    branches: 
    - main 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing
        uses: StavBenSimchon/gh-action-example@main
        with:
          is_ci: 'true'
          test_flag: 'true'
          who-to-greet: test
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: get jq
        run: apt install jq
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)